language: ruby
sudo: false
cache: bundler
rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - jruby-9.2.9.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
before_install:
  - gem update --system
  - gem install bundler -v 2.0.2
